### ISSUE TITLE
container, travis CI setup and tests

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer-app#1]
Hi @tech4GT ! looking cool! I think perhaps next steps would be to set up TravisCI, and potentially a Dockerfile? 

Then we can think about some basic tests. Great start here!

* [x] dockerfile
* [x] Travis
* [x] tests -exist
* [x] tests -- passing

**Comment by jywarren** [comment]
Also heads up i changed the default branch to `main` -- best to do that early on to avoid issues later!

**Comment by jywarren** [comment]
@icarito I think once this starts to come together, we can begin working on getting this running in Google Cloud!

**Comment by tech4GT** [comment]
Hi jeff, basic tests are running and travis is setup, but its failing while the tests run fine on my machine, would have to debug this!

**Comment by jywarren** [comment]
Ah, here? https://github.com/publiclab/image-sequencer-app/pull/2 Will comment there.

**Comment by jywarren** [comment]
Er, actually can you open a new PR where we can debug that? https://travis-ci.com/publiclab/image-sequencer-app/builds/100217381

**Comment by tech4GT** [comment]
<img width="1439" alt="screen shot 2019-02-08 at 11 23 12 pm" src="https://user-images.githubusercontent.com/25617855/52496117-87b23e00-2bf8-11e9-84df-4a4a220cf7e1.png">

**Comment by tech4GT** [comment]
I'll look into this tomorrow!

**Comment by jywarren** [comment]
awesome!

**Comment by tech4GT** [comment]
Opening a PR to debug this now!

**Comment by tech4GT** [comment]
Hi @jywarren I have fixed the tests and added some more! This is now ready to be deployed as a docker container, so priority list right now is:
- Deploy this to google cloud engine as a docker container
- Fully opaque meta modules
- Optimizations to pixelManipulation API

**Comment by tech4GT** [comment]
@icarito Can you share some resources related to deployment here? Thanks :)

**Comment by tech4GT** [comment]
@jywarren @icarito I have setup docker too, we can now deploy this to gCloud, Also now we can independently work on stuff in is like optimizations and meta-modules.

**Comment by jywarren** [comment]
Wow this is cool. We issued you a Google cloud functions account, did you
see? You should be able to plug in a node module via npm!

**Comment by tech4GT** [comment]
I did not! Where can I find the credentials?

**Comment by jywarren** [comment]
I sent them to your email, did you see?

**Comment by tech4GT** [comment]
I don't think I got it, could you send it again please?

**Comment by jywarren** [comment]
Updated this now that we have tests, docker, Travis, just need to ensure the tests pass and respect the new format in #6 -- Great!!!
