### ISSUE TITLE
Code organization and documentation

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer-app#11]
This is looking really good. What do you think of:

* [x] filling out the README a bit
* [x] labeling the `converter` system as specifically a MapKnitter exporter function?

Any other changes to this repository to balance the specific use case of `mapknitter-exporter` (`mapknitter-exporter-js`?) with a generalized `image-sequencer-express`?

**Comment by jywarren** [comment]
With proper documentation (see https://github.com/publiclab/mapknitter-exporter-sinatra/ and https://github.com/publiclab/mapknitter-exporter/) as a `mapknitter-exporter-js` this would be great. But if it's to be a general-purpose tool that could be a sub-section of the README.

**Comment by tech4GT** [comment]
Alright! @jywarren I'll get started on this right away! We'll also need to update tests and add some for the new multiSequencer server!
So I suppose we can keep the repository as is-app which is a general tool but then add a section to the readme about how to use this to export mapknitter maps!

**Comment by jywarren** [comment]
Great!

**Comment by jywarren** [comment]
OK, one thing I'd like to make really clear is how to initiate an export from a warpables.json address -- referencing your work here: https://github.com/publiclab/image-sequencer-app/issues/10#issuecomment-496318514

Note how the Ruby version has a simple syntax like this:

http://export.mapknitter.org/export?url=https://mapknitter.org/maps/pvdtest/warpables.json&scale=30 (although you can also POST the .json alternatively)

Is it this, right now?

https://us-central1-public-lab.cloudfunctions.net/is-function-edge/api/v1/convert?url=https://mapknitter.org/maps/ceres--2/warpables.json

**Comment by tech4GT** [comment]
Oh, Actually I made it a 2 part process, I'll add an export route in right now!
it should look like this:
`baseURL/export/?url=https://mapknitter.org/maps/pvdtest/warpables.json`

**Comment by jywarren** [comment]
great!

**Comment by tech4GT** [comment]
Okay @jywarren I have refactored everything and the final urls to access the exporter will be(locally):

Start command: `npm run start`

Using linear server: `localhost:4000/api/v1/export/?url=https://mapknitter.org/maps/pvdtest/warpables.json`

Using parallelized server: `localhost:4000/api/v2/export/?url=https://mapknitter.org/maps/pvdtest/warpables.json`

**Comment by tech4GT** [comment]
I think this new one works much better, since we can compare the runtimes on the save server instance! :smile:

**Comment by jywarren** [comment]
that's awesome. Great work! Can we test this even before setting up the
cluster?

**Comment by tech4GT** [comment]
I mean I tried this out on cloud functions but it runs out of memory! The v2 api works insanely fast on my machine though! It's like half the time compared to v1 !

**Comment by tech4GT** [comment]
You can try it out locally maybe?

**Comment by jywarren** [comment]
no, it's OK - let's just wait for @icarito to help us get this installed in
a cluster.

**Comment by jywarren** [comment]
Hi @icarito so the cluster should now use this?

http://34.74.118.242/api/v2/process/?steps=[%7B%22id%22:1,%22input%22:%22https://s3.amazonaws.com/grassrootsmapping/warpables/312455/test.png%22,%22depends%22:[],%22steps%22:%22webgl-distort%7Bnw%3A169%252C166%7Cne%3A0%252C104%7Cse%3A40%252C0%7Csw%3A214%252C45%7D%22%7D,%7B%22id%22:2,%22input%22:1,%22depends%22:[1],%22steps%22:%22canvas-resize%7Bwidth:428%7Cheight:332%7Cx:0%7Cy:0%7D%22%7D]

**Comment by jywarren** [comment]
@tech4gt just reporting from @icarito here:

I tried this URL:
http://34.73.7.193/api/v2/export/?url=http://mapknitter.org/maps/pvdtest/warpables.json&scale=30

and now I also did kubectl logs [container-id-from-kubectl-get-pods] and I can see the app log:


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:22) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

Looks like a missed dependency in the Docker container!

**Comment by tech4GT** [comment]
Hi @jywarren this looks weird! It looks like the server was unable to launch chromium for some reason! Maybe chromium was not saved as a dependency in the package.json file!!

**Comment by jywarren** [comment]
Hmm, well hopefully you'll soon be able to push up new versions just by pushing! 

see @icarito's work in https://github.com/publiclab/image-sequencer-app/pull/17

**Comment by tech4GT** [comment]
@jywarren I currently do not have my personal computer and I would have to reconfigure git on this one in order to commit! Could you please just run the command `npm install --save chromium` ??

**Comment by jywarren** [comment]
Does the dockerfile need additional configuration?

**Comment by tech4GT** [comment]
> Hmm, well hopefully you'll soon be able to push up new versions just by pushing!
> 
> see @icarito's work in #17

Wow! This looks fantastic!!

**Comment by jywarren** [comment]
I'm actually on my phone right now, about to board a plane. But we'll try this soon, it should be a new PR with the package.json and lockfile after running that command, right?

**Comment by tech4GT** [comment]
> Does the dockerfile need additional configuration?

I don't think so!

**Comment by tech4GT** [comment]
> I'm actually on my phone right now, about to board a plane. But we'll try this soon, it should be a new PR with the package.json and lockfile after running that command, right?

Yeah! That should do the trick! Otherwise I'll look into this as soon as possible!

**Comment by tech4GT** [comment]
Oh no wait, that should not be required!

**Comment by tech4GT** [comment]
Okay, I'm a little confused here! I cloned and tried running it and it worked on my machine. Okay @jywarren I'll figure this out and paste my findings here! Thanks!

**Comment by jywarren** [comment]
Awesome, thanks! I'm almost taking off now :-)

**Comment by tech4GT** [comment]
Okay I think in order to run puppeteer inside docker we have to launch it with the no-sandbox tag
Details here : https://stackoverflow.com/questions/43665276/how-to-run-google-chrome-headless-in-docker/51863447

**Comment by tech4GT** [comment]
Raising an issue on image-sequencer for this!

**Comment by tech4GT** [comment]
Alright found it! We need to install chrome separately inside the container! I found a sample dockerfile here https://hub.docker.com/r/alekzonder/puppeteer/dockerfile
@jywarren I'm stop by my house in a couple of hours and put in the pr! :tada:

**Comment by jywarren** [comment]
... this works!!!

http://34.74.118.242/api/v2/export/?url=http://mapknitter.org/maps/pvdtest/warpables.json&scale=30

**Comment by jywarren** [comment]
This is taking a while but it's MUCH bigger -- 3 multi-megabyte images

**Comment by jywarren** [comment]
OK LOL this was scary... it completed, was really giant, and i started scrolling...

![image](https://user-images.githubusercontent.com/24359/59230571-da523580-8bab-11e9-9322-953195e0e15b.png)

**Comment by jywarren** [comment]
How did that happen? it redirected to: `http://34.74.118.242/api/v2/process/?steps=[%7B%22id%22:1,%22input%22:%22https://s3.amazonaws.com/grassrootsmapping/warpables/306187/DJI_1207.JPG%22,%22depends%22:[],%22steps%22:%22webgl-distort%7Bnw%3A0%252C1708%7Cne%3A320%252C0%7Cse%3A1529%252C220%7Csw%3A1209%252C1928%7D%22%7D,%7B%22id%22:2,%22input%22:%22https://s3.amazonaws.com/grassrootsmapping/warpables/306188/DJI_1205.JPG%22,%22depends%22:[],%22steps%22:%22webgl-distort%7Bnw%3A371%252C1908%7Cne%3A691%252C251%7Cse%3A1911%252C478%7Csw%3A1618%252C2107%7D%22%7D,%7B%22id%22:3,%22input%22:%22https://s3.amazonaws.com/grassrootsmapping/warpables/306189/DJI_1202.JPG%22,%22depends%22:[],%22steps%22:%22webgl-distort%7Bnw%3A1596%252C2153%7Cne%3A1912%252C503%7Cse%3A2976%252C597%7Csw%3A2836%252C2232%7D%22%7D,%7B%22id%22:4,%22input%22:1,%22depends%22:[1,2,3],%22steps%22:%22canvas-resize%7Bwidth:5952%7Cheight:4464%7Cx:0%7Cy:0%7D,import-image%7Burl:output%3E2%7D,overlay%7Bx:371%7Cy:251%7D,import-image%7Burl:output%3E3%7D,overlay%7Bx:1596%7Cy:503%7D%22%7D]`

Uhhhhhhh it's because I have this installed maybe? https://chrome.google.com/webstore/detail/make-america-kittens-agai/klchnmggepghlcolikgaekpibclpmgcm

This is funny.

**Comment by jywarren** [comment]
I uninstalled the extension ☹️ and am re-running it.

**Comment by jywarren** [comment]
It worked!!!! 25mb output in <2 minutes!

Too big even to upload to GitHub! https://www.dropbox.com/s/m6v131cyynlwx0a/ceres--2.png?dl=0

**Comment by jywarren** [comment]
Here's the timing: 
![image](https://user-images.githubusercontent.com/24359/59231496-d2e05b80-8bae-11e9-9674-528cec9bb25c.png)

**Comment by jywarren** [comment]
Moving to #19 !!!!
