### ISSUE TITLE
Change "extra space" fixes

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer-app#13]
https://github.com/publiclab/image-sequencer-app/blob/5cdf8559cfdb95c65ddc2589403dcc273c1f3661/src/util/converter.js#L50

Hi Varun, I could be at the wrong spot here, but I think in the original code corresponding to this, we used the largest dimension to set the size: 

https://github.com/publiclab/mapknitter-exporter/blob/c767780392342c109b26a887971b3ab6bcd98c94/lib/mapknitterExporter.rb#L136

Is this a bit less arbitrary than the fix you've used? Or, what are next steps to address this quick fix? Thanks!

**Comment by tech4GT** [comment]
Oh yes! This was a temporary fix! This issue is related to the one I have just opened #15 , once we have the scaling done right this space won't be needed!

**Comment by jywarren** [comment]
OK, great. Super!
