### ISSUE TITLE
Adjust scaling with parameter

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer-app#14]
We scale the output image with a provided `cm per pixel` value called `scale` or sometimes `resolution` -- here is the relevant segment -- but also search for `scale` or `pxperm` in this file!

https://github.com/publiclab/mapknitter-exporter/blob/c767780392342c109b26a887971b3ab6bcd98c94/lib/mapknitterExporter.rb#L125-L126

It's not super complex, it's just a scaling factor because we know the real-world dimensions of the images, and we know the pixel dimensions as well. 

cc @tech4GT !

**Comment by tech4GT** [comment]
Awesome! I'll ad this part in tomorrow as well! This is coming together rather quickly!! Exciting!!

**Comment by jywarren** [comment]
yes it's super exciting to see it all happening :-)))))

**Comment by tech4GT** [comment]
Okay I tried running this with node v10 to export a 11904x8928 Image and it is taking somewhere in the neighborhood of about 4-5 minutes on my machine!

**Comment by jywarren** [comment]
that's great - esp. compared to the 8000x14000 image that Ruby ran in 10
minutes.

However, it'll depend in part on how may sub-images it's made up of.
Another great reason to start benchmarking!

**Comment by tech4GT** [comment]
Yes! I better sleep now but I think I can push everything we talked about tomorrow itself! :smile:

**Comment by jywarren** [comment]
go sleep! goodness! yikes i can't imagine what time it is there :-)

Great work today!!!

**Comment by jywarren** [comment]
Hi @tech4gt did the scaling code get added in and would you mind adding some brief docs? Thanks!!

**Comment by tech4GT** [comment]
@jywarren The scaling part was still giving me trouble. I'll add the details in a couple of hours.

**Comment by tech4GT** [comment]
Okay, here is the detailed explanation of the problem:
- We use a converter function to convert the lat/long coordinates to overlay coordinates of warped images.
- While the coordinates generated are distorting the image correctly they are getting scaled incorrectly which results in improper overlay of images.
- We need to fix the converter in a way that it consumes a scale query and converts the coordinates into correct overlay coordinates for every value of the scale and not just a particular value.

**Comment by jywarren** [comment]
We may need to use the haversine formula if we're not already doing so to correctly scale: https://www.npmjs.com/package/haversine-distance

**Comment by jywarren** [comment]
Hmm here are the sections where scaling might be needed. We probably need a scale coefficient. 
https://github.com/publiclab/image-sequencer-app/blob/9afad914c75020d036a2f139be144b0d4ca6e6ae/src/api/v2/util/converter-multiSequencer.js#L60-L63

I couldn't find a commit referencing scale, or code referencing a scale parameter. Is this in a feature branch somewhere? Can you open a PR? Thanks!

We can refer to the matching section of code in mapknitter-exporter, which does the same thing but in Ruby and ImageMagick:

https://github.com/publiclab/mapknitter-exporter/blob/main/lib/mapknitterExporter.rb#L251

**Comment by tech4GT** [comment]
Yeah, I was kind of trying this stuff out when we decided to circle back later. I couldn't really figure out how to convert the parameters using scale though, by looking at the ruby code!
I'll try this out tomorrow, and add the code I wrote for consuming the scale parameter(It's on my local machine right now, sorry). That wan't really working perfectly though!

**Comment by tech4GT** [comment]
The npm module looks great! It might just make the job easier for us!!

**Comment by tech4GT** [comment]
And now since the deployment stuff is figured out, this is all that remains I guess :smile:

**Comment by tech4GT** [comment]
@jywarren Is there someone I can talk to maybe? Someone who worked on the ruby version, maybe they'll be able to better explain this part of the logic to me. I still can't really wrap my head around this!

**Comment by jywarren** [comment]
Probably myself... would you have time to join the Code Open Call tomorrow?

https://everytimezone.com/s/adff8f42

https://publiclab.org/opencall

Thanks, Varun!

**Comment by tech4GT** [comment]
It’s in the evening, I think I can make it! Thanks!

**Comment by jywarren** [comment]
OK so placement is incorrect - but rotation and distortion are good. Let's then look at this segment of code:

https://github.com/publiclab/mapknitter-exporter/blob/main/lib/mapknitterExporter.rb#L250-L282

**Comment by tech4GT** [comment]
https://github.com/publiclab/image-sequencer-app/issues/23
