### ISSUE TITLE
Error while overlaying!

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer-app#15]
The overlay positions of distorted images are not correct! 
Here's the link to the code where I calculate the corner points for distortion https://github.com/publiclab/image-sequencer-app/blob/8dd6aa43d174fe31d1c279bcf29359ef5afb7977/src/api/v2/util/converter-multiSequencer.js#L37
Cc @jywarren

**Comment by tech4GT** [comment]
Hi @jywarren I guess you’re really busy right now! I’ve been trying to reach you on email with the state of the project. Please check that out whenever you can find the time. Thanks!

**Comment by jywarren** [comment]
Oh I'm so sorry! Will check ASAP
