### ISSUE TITLE
Incorrect overlay Problem

### ISSUE THREAD

**Issue by tech4GT** [publiclab/image-sequencer-app#23]
## The issue:
The distorted images are not being overlaid correctly with respect to each other on the final canvas.

The logic to calculate the distortion and overlay coordinates happens inside the converter util.
https://github.com/publiclab/image-sequencer-app/blob/dev/src/api/v2/util/converter-multiSequencer.js

## Steps to reproduce the issue locally:
1. Please clone the `dev` branch.
2. run `npm i`
3. run `npm run start`

The images are getting distorted correctly, to test that we can use this url:
`http://localhost:4000/api/v2/export/?url=http://mapknitter.org/maps/pvdtest/warpables.json`

Since the upload query param is not set, this should return the correctly distorted image as a response to the browser. I have added Logs on each step so it should be easy to see the status of the request.

![download](https://user-images.githubusercontent.com/25617855/60943598-14763a80-a304-11e9-9936-28d056a6bad5.png)

Now, moving on to multi-image maps, we can use the ceres map to see the relative positioning of the images.

Using this endpoint `http://localhost:4000/api/v2/export/?url=https://mapknitter.org/maps/ceres--2/warpables.json`
This should return the 3 images distorted and overlaid on a canvas but they won't quite match up.
![Screenshot 2019-07-10 at 11 21 05 AM](https://user-images.githubusercontent.com/25617855/60943873-e80eee00-a304-11e9-9a3f-b79cdc5b41d9.png)

*Please Do not run this with larger image maps since the browser will make repeated requests to the server and you will not see any response.*

**Comment by tech4GT** [comment]
cc @jywarren

**Comment by jywarren** [comment]
Can you show with a screenshot what it's supposed to look like?

**Comment by jywarren** [comment]
Thanks!

**Comment by jywarren** [comment]
Ah here, i can!

![image](https://user-images.githubusercontent.com/24359/61006155-a6e40180-a337-11e9-915d-8f21faa03f72.png)

Like this?

**Comment by jywarren** [comment]
Hey, it looks like perhaps you're just overlaying them in reverse order?

**Comment by tech4GT** [comment]
I'm sorry, how's that? I mean the order of overlay won't change their relative positions right?

**Comment by jywarren** [comment]
Ah, i'm sorry, i didn't look close enough. Here they are overlaid:

![image](https://user-images.githubusercontent.com/24359/61073283-15ca6480-a3e3-11e9-8de9-e1dfcf0c69b5.png)

It looks like there may be a couple possible issues, because it doesn't look like you've simply got the x-axis scale wrong, it seems the rightmost image is actually taller than it should be as well. 

But we should remember that on MapKnitter it's shown in spherical mercator, whereas you're working in unprojected lat/lon, so maybe that part is OK. Most importantly it looks like the overlaps aren't right. Let me look closer...

**Comment by jywarren** [comment]
Hmm. the Ruby code relies on `gdalwarp` to figure this all out, though it does it in pure lat/lon as well: https://github.com/publiclab/mapknitter-exporter/blob/main/lib/mapknitterExporter.rb#L278

**Comment by jywarren** [comment]
Sorry, what's going on here? Maybe we should add a comment? 

https://github.com/publiclab/image-sequencer-app/blob/560be723d34d16fabe30fb3a38adeedbfc98cbd0/src/api/v2/util/converter-multiSequencer.js#L25-L28

**Comment by tech4GT** [comment]
Oh, I added that temporarily, it brings the final canvas size in range of the max allowed array size. We should be able to remove this once we use scale to determine the final size.

**Comment by jywarren** [comment]
Hmm, actually, how is `width` determined? If it's just the pixel width of the image, then we're mixing latitudes/longitudes with pixel dimensions... 

https://github.com/publiclab/image-sequencer-app/blob/560be723d34d16fabe30fb3a38adeedbfc98cbd0/src/api/v2/util/converter-multiSequencer.js#L7

**Comment by tech4GT** [comment]
Oh, OK! So the width field in the json represents the actual image width then?

**Comment by tech4GT** [comment]
Oh, OK! So the width field in the json represents the actual image width then?

**Comment by jywarren** [comment]
Can you write a simple test for `convert`? That might help us debug that section. Right now I can't see what's being passed into it -- hmm. 

Actually I don't think you need to be using the `width` parameter here... let me think about `webgl-distort` for a sec...

**Comment by jywarren** [comment]
Hmm. OK, so https://github.com/publiclab/image-sequencer/blob/main/src/modules/WebglDistort/info.json can already determine the height and width of the image, so it doesn't need `width` or `height` passed in, i think.

**Comment by tech4GT** [comment]
Oh okay! This makes sense then!
What I did was make the final width and height of the canvas as the sum of the individual heights of all images! Then I just scaled from latitude and longitude to this final width and height!

**Comment by tech4GT** [comment]
> Hmm. OK, so https://github.com/publiclab/image-sequencer/blob/main/src/modules/WebglDistort/info.json can already determine the height and width of the image, so it doesn't need `width` or `height` passed in, i think.

Yeah it just needs the four corner points.

**Comment by tech4GT** [comment]
> Hmm. OK, so https://github.com/publiclab/image-sequencer/blob/main/src/modules/WebglDistort/info.json can already determine the height and width of the image, so it doesn't need `width` or `height` passed in, i think.

Yeah it just needs the four corner points.

**Comment by tech4GT** [comment]
Do you think If we do not scale at all, it will work??

**Comment by jywarren** [comment]
So maybe this should be:

```js
coords.push({
  x: Math.round((node.lon - minX) / (maxX - minX)),
  y: Math.round((node.lat - minY) / (maxY - minY))
});

```

But there's another problem - and this might be our issue -- we can't round lat/lon because even 0.000 is a matter of meters!

**Comment by tech4GT** [comment]
Oh wait!! Another issue!! I just checked the json and the lat, lon values are strings! They need to be parsed first!

**Comment by tech4GT** [comment]
> So maybe this should be:
> 
> ```js
> coords.push({
>   x: Math.round((node.lon - minX) / (maxX - minX)),
>   y: Math.round((node.lat - minY) / (maxY - minY))
> });
> ```
> 
> But there's another problem - and this might be our issue -- we can't round lat/lon because even 0.000 is a matter of meters!

Actually this is why I decided to scale it in the first place!

**Comment by jywarren** [comment]
For now, let's not scale. Once we convert to true projected `x,y` and not `lat,lon`, that'll involve a projection function that will require a scale, like in this example:

```
    scale = 20037508.34    
    y1 = pxperm.to_f * Cartagen.spherical_mercator_lat_to_y(northmost,scale)
```

Here actually `pxperm` is the scale value we want -- pixels per meter. `scale` in this example is just like the diameter of the earth or something :-)

**Comment by tech4GT** [comment]
Okay so pxperm is consumed via the query parameter then, correct?

**Comment by jywarren** [comment]
the passed `scale` query parameter is in pixels per meter, yeah. 

So if we must convert to pixels here, let's use a projection:

https://github.com/publiclab/image-sequencer-app/issues/10#issuecomment-488300097

**Comment by jywarren** [comment]
instead of an arbitrary scale factor.

**Comment by tech4GT** [comment]
Okay, this makes sense! So we ditch the current way of calculating height and width and then using px_per_m we can compute the final height and width of the image, correct?

**Comment by jywarren** [comment]
well, the values we pass into the webgl-distort module can be used to calculate the final height and width, so yeah, the values passed in originally are actually pre-distortion values. Maybe that's one thing that was broken!

**Comment by tech4GT** [comment]
Okay, So I am finally starting to understand this! Yay!
Let me make some changes like you suggested and add a test like you asked and we can pick this up from there! 😃

**Comment by tech4GT** [comment]
One more thing, what do we do if according to the given scale the size of the final canvas is too big for javascript array? Should we just reject the request then? Or modify the scale in some way?

**Comment by jywarren** [comment]
AWESOME!

**Comment by jywarren** [comment]
Perhaps we can return an error that says it's too big; is it possible to
return a recommended maximum possible scale?

**Comment by tech4GT** [comment]
Yeah I think we should be able to figure that out based on the node version! So we just return that in the response! Awesome!

**Comment by tech4GT** [comment]
![download (1)](https://user-images.githubusercontent.com/25617855/61184621-93a1a080-a66d-11e9-8f12-cd2e992d70a9.png)

**Comment by tech4GT** [comment]
@jywarren I tried the fixes we discussed and that breaks the distort!! :(
I would have to look into this more! Please give me just a little more time to figure this out!

**Comment by tech4GT** [comment]
Looks like the image was converted into it's reflection and the coordinates are all wrong!

**Comment by jywarren** [comment]
Hm, can you point me at the commit for the new changes?

**Comment by tech4GT** [comment]
> Hm, can you point me at the commit for the new changes?

https://github.com/publiclab/image-sequencer-app/commit/7cbc347a13dd8ea52a63e758109f69f83e72cd57

**Comment by tech4GT** [comment]
Also I found this article for calculating the distance, can you please have a look at it and see if it is correct? Thanks.
https://stackoverflow.com/questions/27928/calculate-distance-between-two-latitude-longitude-points-haversine-formula/21623206#21623206

**Comment by jywarren** [comment]
Ah yes! That would work. there's also a package: https://www.npmjs.com/package/haversine-distance

**Comment by jywarren** [comment]
I left a comment on the commit. But maybe best to use PRs so I can inline comment? 

https://github.com/publiclab/image-sequencer-app/commit/7cbc347a13dd8ea52a63e758109f69f83e72cd57

Thanks!

**Comment by jywarren** [comment]
If we must project, then let's use these resources, copying from #10:

> For starters, we can simply use `lat/lon` and scale them to use as pixel values. But a follow-up step will require using converters from `lat/lon` to `x,y`; there are a few available, such as:

* https://github.com/jywarren/cartagen/blob/b348dd06e2d1a69936826e9ef4e6f9fa0ed4a060/src/mapping/projection.js#L45-L50
* http://proj4js.org/ (not sure how to use this one, but think it'd be `proj4("WGS84", "EPSG:3857", [lon, lat])`)
* Leaflet's `latLngToContainerPoint(<LatLng> latlng)` - https://leafletjs.com/reference-1.4.0.html#map-latlngtocontainerpoint although we would have to initialize a map to use it

**Comment by tech4GT** [comment]
Hi @jywarren 
I have been putting in some work here it's just not coming out right. I have tried a number of different approaches, even by using the cosine formula to compute exact distances.
I get the feeling that the metadata is just not right, are there other services which use the same metadata??

**Comment by tech4GT** [comment]
> Ah yes! That would work. there's also a package: https://www.npmjs.com/package/haversine-distance

So I tried this too and this is the result I am getting, which is just not quite right! :(
<img width="292" alt="Screen Shot 2019-08-14 at 11 09 38 PM" src="https://user-images.githubusercontent.com/25617855/63042884-a74c5b00-bee8-11e9-8677-882b88b399d4.png">

**Comment by jywarren** [comment]
Hi, sorry, which metadata is not quite right? And, can you compare the
image you attached to the one shown in the web interface for comparison
purposes, in a screenshot? Thanks!

**Comment by tech4GT** [comment]
Sure, https://mapknitter.org/maps/pvdtest/
This is the one!

PS I'm not sure , just a hunch! :sweat_smile:

**Comment by tech4GT** [comment]
For some reason my screenshot won't upload, could you take a look through the web interface please?

**Comment by tech4GT** [comment]
https://mapknitter.org/maps/pvdtest/warpables.json this is the metadata.

**Comment by jywarren** [comment]
OK, looking today -- but also noting I did a screencast of using MapKnitter with the Ruby exporter, so you can see how that lifecycle works in detail: https://github.com/publiclab/mapknitter/issues/919#issuecomment-522020038 -- I hope that's helpful context!

**Comment by jywarren** [comment]
OK, for comparison: 

![image](https://user-images.githubusercontent.com/24359/63183537-2e055300-c023-11e9-9e03-586f9f901b50.png) ![image](https://user-images.githubusercontent.com/24359/63183544-32317080-c023-11e9-9730-fe2016c114af.png)

**Comment by jywarren** [comment]
The metadata is correct, as it's being used in the Ruby export process, generating (note that this version blurs the edges, but you can still see the distortion):

![image](https://user-images.githubusercontent.com/24359/63183674-93594400-c023-11e9-8139-265752f2c692.png)

**Comment by jywarren** [comment]
Varun, it looks like your general distortion is OK, but you may be using the points in the wrong order. This could result in both flipping as well as the orientation issues.

**Comment by jywarren** [comment]
OK, i'm going to check the corner ordering. But also, i re-distorted the image, so that it has no symmetries, and will be easier to tell if it's flipped or rotated or stretched or whatever:

![image](https://user-images.githubusercontent.com/24359/63193515-b132a300-c03b-11e9-86e2-3dd594d6b170.png)![image](https://user-images.githubusercontent.com/24359/63184030-78d39a80-c024-11e9-87b7-46f4a0a94456.png)

**Comment by tech4GT** [comment]
Hmm, so do you thing the image is flipped horizontally?
I'm sure that changing the order of points won't really change much but it'll rotate the image in the same distortion since the corner points did not change!

**Comment by tech4GT** [comment]
I tried this using the following formula too:
```js
{ x: (node.lon - minX) / (maxX - minX) * scale, y: (node.lat - minY) / (maxX - minX) * scale }
```
This gives the following coordinates with scale 5
```json
[ { x: 190.76910075466273, y: 143.63765881829983 },
  { x: 181.79171961031517, y: 0 },
  { x: 0, y: 28.054313199386918 },
  { x: 8.977381144378233, y: 171.69180522627062 } ]
```

**Comment by jywarren** [comment]
I'm installing it locally now, but the flip could also come from not
setting the sign of latitude or longitude correctly, or by reversing lat
and lon -- some conversion equations use a reversed convention... i.e. set
0,0 to SE instead of NW or something like that...

**Comment by jywarren** [comment]
Gah, i can't get chrome to boot on my chromebook. I think it needs more memory. Let me think on how to get this running locally.

**Comment by jywarren** [comment]
Looking, and we should be able to pass the text of https://mapknitter.org/maps/pvdtest/warpables.json directly to the `convert(arr)` function, and get a sequencer string. I'll try that, and just run it locally in node, if I can. 

```
[{"id":312455,"parent_id":null,"image_content_type":"image/png","image_file_name":"test.png","thumbnail":null,"image_file_size":103148,"width":214,"height":166,"created_at":"2019-04-30T20:40:21.000Z","updated_at":"2019-08-16T16:50:41.000Z","map_id":13238,"nodes":[{"id":2723878,"color":"black","author":"warren","lat":"41.8200378187","lon":"-71.4034409085","way_id":0,"order":0,"created_at":"2019-08-16T16:50:41.000Z","updated_at":"2019-08-16T16:50:41.000Z","name":"","description":"","map_id":0,"way_order":0,"body":null},{"id":2723879,"color":"black","author":"warren","lat":"41.8199873593","lon":"-71.4030021564","way_id":0,"order":0,"created_at":"2019-08-16T16:50:41.000Z","updated_at":"2019-08-16T16:50:41.000Z","name":"","description":"","map_id":0,"way_order":0,"body":null},{"id":2723880,"color":"black","author":"warren","lat":"41.8196229772","lon":"-71.4029728831","way_id":0,"order":0,"created_at":"2019-08-16T16:50:41.000Z","updated_at":"2019-08-16T16:50:41.000Z","name":"","description":"","map_id":0,"way_order":0,"body":null},{"id":2723881,"color":"black","author":"warren","lat":"41.8198214546","lon":"-71.4034614433","way_id":0,"order":0,"created_at":"2019-08-16T16:50:41.000Z","updated_at":"2019-08-16T16:50:41.000Z","name":"","description":"","map_id":0,"way_order":0,"body":null}],"locked":false,"deleted":false,"history":"","cm_per_pixel":23.0934,"src":"https://s3.amazonaws.com/grassrootsmapping/warpables/312455/test.png","srcmedium":"https://s3.amazonaws.com/grassrootsmapping/warpables/312455/test_medium.png"},{"id":312456,"parent_id":null,"image_content_type":"image/png","image_file_name":"test.png","thumbnail":null,"image_file_size":103148,"width":214,"height":166,"created_at":"2019-04-30T20:40:25.000Z","updated_at":"2019-04-30T20:40:25.000Z","map_id":13238,"nodes":[],"locked":false,"deleted":false,"history":"","cm_per_pixel":0.0,"src":"https://s3.amazonaws.com/grassrootsmapping/warpables/312456/test.png","srcmedium":"https://s3.amazonaws.com/grassrootsmapping/warpables/312456/test_medium.png"}]
```

**Comment by jywarren** [comment]
Hm, ok, i got: 

```
> convert(images)
[ { x: NaN, y: NaN },
  { x: NaN, y: NaN },
  { x: NaN, y: NaN },
  { x: NaN, y: NaN } ]
[]
[ { id: 1,
    input: 'https://s3.amazonaws.com/grassrootsmapping/warpables/312455/test.png',
    depends: [],
    steps: 'webgl-distort{nw%3ANaN%252CNaN%7Cne%3ANaN%252CNaN%7Cse%3ANaN%252CNaN%7Csw%3ANaN%252CNaN}' },
  { id: 2,
    input: 1,
    depends: [ 1 ],
    steps: 'canvas-resize{width:1000|height:1000|x:0|y:0}' } ]
```

That's not right...

**Comment by tech4GT** [comment]
What branch are you on? Are you sure you are running dev?

**Comment by jywarren** [comment]
yes, dev... looking now... 

What's going on here? why is only one based on `node.lat`?

https://github.com/publiclab/image-sequencer-app/blob/a43107f12e01ce545edbcd6b5fb34cef2e801642/src/api/v2/util/converter-multiSequencer.js#L46-L53

**Comment by tech4GT** [comment]
Yeah so I tried a couple of versions of these.
In this version I first find the distance based on lat difference alone, then on lon difference alone.

**Comment by tech4GT** [comment]
This is the lon part
https://github.com/publiclab/image-sequencer-app/blob/a43107f12e01ce545edbcd6b5fb34cef2e801642/src/api/v2/util/converter-multiSequencer.js#L37-L43

**Comment by jywarren** [comment]
OK, let me walk through step at a time.

1. we find the origin of `minX,minY`
2. for each corner, we find the offset, measured from that origin, in pixels

**Comment by tech4GT** [comment]
Not initially, we use the haversine to calculate x and y coordinate of each corner with respect to the origin and then use scale to convert these `meters` to `pixels`

**Comment by jywarren** [comment]
Ah, i passed no scale param. doing now.

**Comment by jywarren** [comment]
`convert(images, 10)` yielded, after I made some changes:

`webgl-distort{nw%3A642.6311735245%252C-376.3761919533%7Cne%3A642.6316122766%252C-376.3762424127%7Cse%3A642.6316415499%252C-376.37660679479995%7Csw%3A642.6311529897%252C-376.3764083174}`

**Comment by jywarren** [comment]
Which put into sequencer as `https://sequencer.publiclab.org/examples/#steps=webgl-distort{nw%3A642.6311735245%252C-376.3761919533%7Cne%3A642.6316122766%252C-376.3762424127%7Cse%3A642.6316415499%252C-376.37660679479995%7Csw%3A642.6311529897%252C-376.3764083174}` yielded:

![image](https://user-images.githubusercontent.com/24359/63187796-bdafff00-c02d-11e9-8f86-3c6dae105788.png)

**Comment by jywarren** [comment]
The canvas resize doesn't work while in the same sequencer, but let me see...

**Comment by jywarren** [comment]
Oh that's weird:

![image](https://user-images.githubusercontent.com/24359/63193711-2aca9100-c03c-11e9-8983-37549f85e2e1.png)

The browser sequencer changed the values to 

`0,100 1023,-50 1223,867 100,767`

instead of (rounding):

`642,-376 642,-376 642,-376 642,-376`

**Comment by jywarren** [comment]
Um, let me check my arithmetic...

**Comment by jywarren** [comment]
OK, also looking at point ordering conventions, as we addressed in the Ruby version: https://github.com/publiclab/Leaflet.DistortableImage/pull/322

**Comment by jywarren** [comment]
OK, my current code is producing, with NW-0, NE-1, SE-2, SW-3:

0, 2, 1, 3 (receiving from warpables.json)

webgl distort wants: 0,1,2,3

**Comment by jywarren** [comment]
Hm. ok, i corrected that but it's now outputting:

```
[ { x: 21, y: 415 },
  { x: 489, y: 0 },
  { x: 459, y: 364 },
  { x: 0, y: 198 } ]
```

I'll push up a commit just to pause for a sec... https://github.com/jywarren/image-sequencer-app/commit/b9b5de1ae5f6d60d6ee8dc43d9d18070d36ee76e

**Comment by jywarren** [comment]
OK, so for comparison, using Leaflet, the pixel coordinates are (they will be scaled, but proportions should be the same):

```
{x: 9, y: 24}
{x: 172, y: 49}
{x: 1, y: 132}
{x: 183, y: 231}
```

**Comment by jywarren** [comment]
OK, I added projection properly, with proj4 (https://www.npmjs.com/package/proj4) -- check it out:

```
[ { x: 7, y: 186 },
  { x: 163, y: 0 },
  { x: 153, y: 163 },
  { x: 0, y: 89 } ]
```

Still not sure. But see https://github.com/publiclab/image-sequencer-app/pull/24 ...

**Comment by jywarren** [comment]
Hmm. I'm not sure now that projection is our problem. It could be ordering. I'm confused, but I even ported in Leaflet's projection functions and used them (https://github.com/Leaflet/Leaflet/blob/dc6a0ae61a70b1d34f9ee2c4f814bdd21841c774/src/geo/projection/Projection.SphericalMercator.js) and I got:

```
[ { x: 7, y: 186 },
  { x: 163, y: 0 },
  { x: 153, y: 163 },
  { x: 0, y: 89 } ]
```

Which is actually exactly what we had from proj4, which is at least comforting. So, what's going on here? I pushed the Leaflet code to #24 as well, not that it helped.

**Comment by jywarren** [comment]
Hey wait, is this the right thing, upside down?

![image](https://user-images.githubusercontent.com/24359/63201762-9fa9c500-c054-11e9-9f5e-f1f5b3ba7df9.png)

**Comment by jywarren** [comment]
Compare to 
![image](https://user-images.githubusercontent.com/24359/63201772-a89a9680-c054-11e9-82df-af5bfccdb86d.png)

**Comment by jywarren** [comment]
Yes!!! It is!!!

![image](https://user-images.githubusercontent.com/24359/63201974-87867580-c055-11e9-92bf-a3103af19648.png)

**Comment by jywarren** [comment]
OK, so we can just use proj4, but we need to reverse the y-values and re-order the coordinates. What do you think???

**Comment by jywarren** [comment]
Reverted to proj4 in https://github.com/publiclab/image-sequencer-app/pull/24 - you can work from this!

**Comment by tech4GT** [comment]
Looking into it!

**Comment by tech4GT** [comment]
Or we could add a 180 degree rotate step??

**Comment by jywarren** [comment]
Made the change in #24!

**Comment by tech4GT** [comment]
@jywarren Moving over from #24 
Working on a module which would resize the image to the desired width and height. After that we should be able to debug the overlay issue more clearly!

**Comment by jywarren** [comment]
awesome!

**Comment by tech4GT** [comment]
Okay I think this should work https://www.npmjs.com/package/image-sequencer-app-resize

**Comment by tech4GT** [comment]
Hmm, still not quite right! Let me make sure it does resize correctly.
<img width="470" alt="Screen Shot 2019-08-24 at 9 03 21 PM" src="https://user-images.githubusercontent.com/25617855/63639668-d1a1d380-c6b3-11e9-8267-558da0b70717.png">

**Comment by jywarren** [comment]
Oh, whoa!!! It looks very close, Varun! Great work, i'm sure we're almost
there!!!

**Comment by tech4GT** [comment]
Hi @jywarren 
I think I got the problems with overlay resolved. This is the result currently!
<img width="415" alt="Screen Shot 2019-09-13 at 8 18 50 PM" src="https://user-images.githubusercontent.com/25617855/64871943-e4c91300-d663-11e9-888a-17c6a0d5085b.png">
It does not line up because the resize module which I adapted from the native resize module in image-sequencer isn't working properly on the width so the images are coming out to be narrower than they should be. I'll write a module for resizing from scratch using something like bilinear interpolation now!
Sorry this took so long, I got caught up in some other stuff :sweat_smile:

**Comment by jywarren** [comment]
Ah, i see! The positions do look good and with the width fix, I'm really
optimistic about this! Thanks, Varun!

**Comment by tech4GT** [comment]
Yeah! I tried this out with a bunch of different scale values and it gives the same result for all of them! So I am sure that all we need now is to fix the resize! yay!
About that, the module seems to be working if I hardcode it into image-sequencer! Trying to figure it out.

**Comment by tech4GT** [comment]
Okay, a lot of debugging later, I finally figured this out! So what is happening is that after the distortion the image has some extra space which is not cropped out for some reason! Due to this the final size of the usable area of the image is coming out to be incorrect!
<img width="533" alt="Screen Shot 2019-09-15 at 2 48 39 PM" src="https://user-images.githubusercontent.com/25617855/64919433-2ffc3680-d7c8-11e9-8348-abcee5de0c9f.png">

@jywarren Any ideas how we can fix this?? Or is this expected behavior out of the webgl-distort module??

**Comment by tech4GT** [comment]
The inner rectangle is the whole area of the image but that has some extra space on the right side which was causing the image to come out narrower than we were expecting!

**Comment by tech4GT** [comment]
One solution that comes to my mind is a `trim module` which would trim the image down from the edges up until it finds a row or column with a non zero pixel!

**Comment by tech4GT** [comment]
I tried this! It works!!! :tada: 
<img width="526" alt="Screen Shot 2019-09-16 at 1 06 16 PM" src="https://user-images.githubusercontent.com/25617855/64940903-d86ed100-d882-11e9-8da4-7d4f81a58533.png">

**Comment by tech4GT** [comment]
We might wanna make changes to the wegl-distort module in the long term though!

**Comment by jywarren** [comment]
OK, cool! I see the latest output generated: 

![image](https://user-images.githubusercontent.com/24359/65261253-d81a4400-dad5-11e9-9bdb-b08cbf5703c8.png)

**Comment by jywarren** [comment]
Compare to original:

![](https://user-images.githubusercontent.com/24359/61006155-a6e40180-a337-11e9-915d-8f21faa03f72.png)

**Comment by jywarren** [comment]
Wow, Varun, this looks perfect. Amazing work. 

So is this the initiating URL? I just opened this and it said `This site can’t be reached / 34.74.118.242 refused to connect.` 

http://34.74.118.242/api/v2/export/?url=https://mapknitter.org/maps/ceres--2/warpables.json

**Comment by jywarren** [comment]
Link to #28

**Comment by tech4GT** [comment]
@jywarren I think that's because we are missing the scale, try this:
http://34.74.118.242/api/v2/export/?url=https://mapknitter.org/maps/ceres--2/warpables.json&scale=3

**Comment by jywarren** [comment]
Or is it this? http://34.74.118.242/api/v2/export/?url=https://mapknitter.org/maps/ceres--2/warpables.json&upload=false&scale=50

The previous one had finally redirected to the full longer URL, but then also showed an error. Let's get the README updated so we know how to initiate this? Thanks, Varun! Again, fantastic work!

**Comment by jywarren** [comment]
Let's add that to the README, thanks! But also why am I getting intermittent `refused to connect` messages?

**Comment by tech4GT** [comment]
Actually 50 I think would be too big for it to handle! We could start with something like 5.

**Comment by jywarren** [comment]
oh ok. maybe the scale is implemented differently that in mapknitter-exporter. 50 is a reasonable value there. But we can set up a conversion function and disambiguate later. Great, i'll try!

**Comment by jywarren** [comment]
http://34.74.118.242/api/v2/export/?url=https://mapknitter.org/maps/ceres--2/warpables.json&scale=5

**Comment by tech4GT** [comment]
Try this, it worked: http://34.74.118.242/api/v2/export/?url=http://mapknitter.org/maps/ceres--2/warpables.json&scale=3

**Comment by tech4GT** [comment]
@jywarren I think the warpable needs to use http too!

**Comment by tech4GT** [comment]
> oh ok. maybe the scale is implemented differently that in mapknitter-exporter. 50 is a reasonable value there. But we can set up a conversion function and disambiguate later. Great, i'll try!

Yeah, I think we gotta scale the scale lol.

**Comment by jywarren** [comment]
OK perfect, that worked! 

Can you make a quick edit to the README and actually add this test URL that people can use?  

Let's close this and open a new one for scale.

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer-app/issues/29
