### ISSUE TITLE
Allow CORS posting

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer-app#35]
Now we've implemented #33, and I edited the README to reflect the ability to POST to initiate an endpoint, we need to allow CORS:

$.post("http://34.74.118.242/api/v2/export/", {scale: 30, upload: true, }).done(function(response) {console.log('response')});

POST http://34.74.118.242/api/v2/export/ 500 (Internal Server Error)
send @ application-36d2d4aca752bde59be9ba00946b83dd9ba5c7994bc707e301636830e5ba4fcc.js:34
ajax @ application-36d2d4aca752bde59be9ba00946b83dd9ba5c7994bc707e301636830e5ba4fcc.js:33
kt.<computed> @ application-36d2d4aca752bde59be9ba00946b83dd9ba5c7994bc707e301636830e5ba4fcc.js:33
(anonymous) @ VM43:1
gallery:1 Access to XMLHttpRequest at 'http://34.74.118.242/api/v2/export/' from origin 'http://mapknitter-stable.laboratoriopublico.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

The full docs are reflected here, but we'll need to enable CORS for them to work as shown:


Basic endpoint: `/api/v2/export/?url=http://example.com/warpables.json&scale=<integer>`

Setting `upload=true` will also upload the output to Google Cloud storage, and return a URL to a persistent JSON status file, also at Google Cloud storage, which will be updated progressively to reflect export progress.

A POST request can be sent enclosing a JSON collection of image URLs and coordinates, as follows:

```js
var json = [{"nodes":[
                {"lat":"41.8200378187","lon":"-71.4034409085"},
                {"lat":"41.8199873593","lon":"-71.4030021564"},
                {"lat":"41.8196229772","lon":"-71.4029728831"},
                {"lat":"41.8198214546","lon":"-71.4034614433"}
            ],
            "cm_per_pixel":23.0934,
            "src":"https://s3.amazonaws.com/grassrootsmapping/warpables/312455/test.png"},
            {"nodes":[
                {"lat":"41.819898342","lon":"-71.4035387139"},
                {"lat":"41.819898342","lon":"-71.4028493862"},
                {"lat":"41.8195005594","lon":"-71.4028493862"},
                {"lat":"41.8195005594","lon":"-71.4035387139"}
            ],
            "cm_per_pixel":35.8578,
            "src":"https://s3.amazonaws.com/grassrootsmapping/warpables/320983/test.png"}
        ];

// now we submit the request to the v2 export endpoint:
$.post("http://34.74.118.242/api/v2/export/", {
  scale: 30,
  upload: true,
  collection: json
}).done(function(response) {
  console.log('response');
});
```

**Comment by jywarren** [comment]
here we just need to configure Express to permit CORS

**Comment by tech4GT** [comment]
Alright! I think if I remember correctly there's a cors middleware that should be perfect!

**Comment by tech4GT** [comment]
Alright! Added it! :smiley:

**Comment by jywarren** [comment]
awesome....>!!!!!!!
