### ISSUE TITLE
Img src attr

### ISSUE THREAD

**Issue by harshkhandeparkar** [publiclab/image-sequencer-app#7]
Here
https://github.com/publiclab/image-sequencer-app/blob/48b9a9d64b8901ef6968d39bd31c359e131c04f9/src/api/v1/index.js#L37-L41

The `img` tag that is returned has a src attribute equal to the variable `img`.
But when the Sequencer is run, the `img` is an object and its `url` property is used as its source dataURL.
Here
https://github.com/publiclab/image-sequencer-app/blob/48b9a9d64b8901ef6968d39bd31c359e131c04f9/src/api/v1/index.js#L45

Shouldn't the `url` property be used for the html img tag as well?

I actually don't have a problem with the html, I just wanted to clarify if I have misunderstood the input data. I want to start contributing to this project so I asked this query.

**Comment by harshkhandeparkar** [comment]
@tech4GT @jywarren

**Comment by tech4GT** [comment]
Okay so this is because I update the values in the imgs array in the callbacks.
