### ISSUE TITLE
Improve GCloud index.js

### ISSUE THREAD

**Issue by harshkhandeparkar** [publiclab/image-sequencer-app#8]
I think this file can be improved in many ways.
https://github.com/publiclab/image-sequencer-app/blob/48b9a9d64b8901ef6968d39bd31c359e131c04f9/cloud/index.js#L9-L28

* Firstly, I think `const ts0` and `const t21` are typos and should have been `t0` and `t1` because on line 24, `runtime: t1-t0`. (Please correct me if I'm wrong)
* `exports.helloworld` can be changed to maybe `benchmark` or `test`
* Line 21 and 22 have too much indentation, that can be improved.

**Comment by harshkhandeparkar** [comment]
@jywarren @tech4GT

**Comment by harshkhandeparkar** [comment]
I am ready to work on these issues (the ones which i have opened), I just need approval.

**Comment by tech4GT** [comment]
Well this one is just for documentation purposes though, this is the current deployment as a cloud function that we wrote to test things out. No point putting in time one this :)
